const tableData = {
  main: {
    headers: ['Data Type', 'Description', 'Retention Period'],
    rows: [
      ['Message Content', 'Public messages sent in channels where FBI is present', '30 days*'],
      ['Attachments', 'Files and images shared in public messages', 'As long as the associated message is retained'],
      ['Emojis & Stickers', 'Custom emojis and stickers used in messages', 'As long as at least 1 message references them'],
      ['Channel Metadata', 'Channel names, IDs, and other metadata', 'As long as the channel holds at least 1 message'],
      ['Guild Metadata', 'Guild names, IDs, and other metadata', 'As long as the guild holds at least 1 channel'],
      ['User Data', 'Usernames, avatars, and IDs', 'Up to 3 months**'],
      ['Command Usage Logs', 'Internal logs of commands used, buttons pressed, etc.', '60 days'],
      ['Exports', 'Channel exports generated by users, including messages, attachments, and metadata', '24 hours — one-time download link'],
    ],
  },
  snapshots: {
    headers: ['Data Type', 'Description', 'Retention Period'],
    rows: [
      ['Channels', 'Name, ID, position, topic, and other metadata', 'Up to 7 days*'],
      ['Roles', 'Name, ID, color, permissions, and other metadata', 'Up to 7 days*'],
      ['Channel Permissions', 'Permissions for each role in each channel', 'Up to 7 days*'],
      ['Bans', 'User ID and reason', 'Up to 7 days*'],
    ],
  },
}

function Table({ data }: { data: { headers: string[]; rows: string[][] } }) {
  return (
    <div style={{ overflowX: 'auto', margin: '1.25rem 0' }}>
      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '0.875rem' }}>
        <thead>
          <tr style={{ background: 'var(--surface)' }}>
            {data.headers.map(h => (
              <th key={h} style={{ padding: '0.75rem 1rem', textAlign: 'left', fontSize: '0.6875rem', fontWeight: 700, letterSpacing: '0.06em', textTransform: 'uppercase', color: 'var(--muted)', border: '1px solid var(--line)', whiteSpace: 'nowrap' }}>
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.rows.map((row, i) => (
            <tr key={i} style={{ borderBottom: '1px solid var(--line)' }}>
              {row.map((cell, j) => (
                <td key={j} style={{ padding: '0.8rem 1rem', color: j === 0 ? 'var(--bright)' : 'var(--muted)', fontWeight: j === 0 ? 600 : 400, border: '1px solid var(--line)', lineHeight: 1.6, verticalAlign: 'top' }}>
                  {cell}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function Section({ number, title, children }: { number: string; title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: '3rem' }}>
      <div style={{ display: 'flex', alignItems: 'baseline', gap: '0.875rem', marginBottom: '1.25rem' }}>
        <span style={{ fontSize: '0.6875rem', fontWeight: 700, letterSpacing: '0.1em', color: 'var(--ember)', fontVariantNumeric: 'tabular-nums', flexShrink: 0 }}>
          {number}
        </span>
        <h2 style={{ fontSize: '1.125rem', fontWeight: 700, color: 'var(--bright)', letterSpacing: '-0.025em', margin: 0 }}>
          {title}
        </h2>
      </div>
      <div style={{ paddingLeft: '2.25rem' }}>
        {children}
      </div>
    </section>
  )
}

function P({ children, style }: { children: React.ReactNode; style?: React.CSSProperties }) {
  return (
    <p style={{ fontSize: '0.9375rem', color: 'var(--muted)', lineHeight: 1.8, margin: '0 0 0.875rem', ...style }}>
      {children}
    </p>
  )
}

function Ul({ items }: { items: React.ReactNode[] }) {
  return (
    <ul style={{ margin: '0 0 0.875rem', padding: 0, listStyle: 'none' }}>
      {items.map((item, i) => (
        <li key={i} style={{ display: 'flex', gap: '0.75rem', alignItems: 'flex-start', padding: '0.4rem 0', fontSize: '0.9375rem', color: 'var(--muted)', lineHeight: 1.75 }}>
          <span style={{ flexShrink: 0, marginTop: '0.55rem', width: '5px', height: '5px', borderRadius: '50%', background: 'var(--ember)', opacity: 0.7 }} />
          <span>{item}</span>
        </li>
      ))}
    </ul>
  )
}

function Strong({ children }: { children: React.ReactNode }) {
  return <span style={{ color: 'var(--bright)', fontWeight: 600 }}>{children}</span>
}

function Note({ children }: { children: React.ReactNode }) {
  return (
    <p style={{ fontSize: '0.8125rem', color: 'var(--muted)', lineHeight: 1.7, opacity: 0.75, margin: '0.5rem 0', fontStyle: 'italic' }}>
      {children}
    </p>
  )
}

function SubHeading({ children }: { children: React.ReactNode }) {
  return (
    <h3 style={{ fontSize: '0.9375rem', fontWeight: 700, color: 'var(--bright)', letterSpacing: '-0.02em', margin: '1.5rem 0 0.6rem' }}>
      {children}
    </h3>
  )
}

export default function PrivacyPolicy() {
  return (
    <main style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
      <div style={{ maxWidth: '52rem', margin: '0 auto', padding: '7rem 2rem 6rem', width: '100%' }}>

        <div style={{ marginBottom: '2.5rem', paddingBottom: '2.5rem', borderBottom: '1px solid var(--line)' }}>
          <h1 style={{ fontSize: 'clamp(2rem, 4vw, 3rem)', letterSpacing: '-0.045em', lineHeight: 1.05, marginBottom: '0.875rem' }}>
            Privacy Policy
          </h1>
          <p style={{ fontSize: '0.875rem', color: 'var(--muted)' }}>
            Version 4 &nbsp;·&nbsp; Last updated June 15, 2026
          </p>
        </div>

        <Section number="01" title="Definitions">
          <P>In this Privacy Policy, the following terms have the meanings set forth below:</P>
          <Ul items={[
            <><Strong>"FBI"</Strong> refers to the Fox Box Insurance Discord bot and its related services.</>,
            <><Strong>"User"</Strong> refers to any individual or entity that interacts with FBI, including server owners, administrators, moderators, and regular server members.</>,
            <><Strong>"Data"</Strong> refers to any information collected by FBI, including but not limited to public messages, attachments, and icons.</>,
            <><Strong>"Discord"</Strong> refers to the Discord platform where FBI operates — we do not own or control Discord in any capacity.</>,
            <><Strong>"Guild"</Strong> refers to a Discord server where FBI is invited and operates.</>,
          ]} />
        </Section>

        <Section number="02" title="Information We Collect">
          <P>FBI collects the following types of information for the purpose of operating and its services:</P>
          <Ul items={[
            'Guild IDs, Channel IDs, User IDs, and Message IDs (for core functionality)',
            'Message content and metadata from public channels',
            'Attachments, emojis, stickers, and embeds shared in public messages',
            'Channel, role, and ban metadata (for server snapshots)',
            'User avatars and usernames (for display purposes)',
            'Command usage and interaction data for internal logs and analytics',
          ]} />
          <P>FBI does not collect data from private channels, direct messages, or group chats unless it is explicitly invited and permitted access to those channels.</P>
        </Section>

        <Section number="03" title="How We Use Your Information">
          <P>We collect data strictly for the following purposes:</P>
          <Ul items={[
            'To provide the logging, exporting, and archival features of FBI',
            'To assist server moderation efforts and ensure accountability',
            'To improve our services and develop new features',
          ]} />
          <P>We do not sell, rent, or lease your data to third parties. We do not use your data for targeted advertising or marketing purposes. Your data will never be shared with third parties unless required by law or in response to a valid legal request such as CSAM.</P>
        </Section>

        <Section number="04" title="How Information is Protected">
          <P>We take the security of your data <Strong>very</Strong> seriously and implement multiple security measures to protect it. While we cannot give exact details about how this is done, we can assure you that we use industry-standard encryption and security practices to protect your data from unauthorized access, disclosure, or destruction. We also regularly review our security practices to ensure they remain effective. Messages are stored in a secure, private database and are encrypted at rest.</P>
        </Section>

        <Section number="05" title="Data Retention">
          <P>We retain your data for as long as necessary to provide our services and fulfill the purposes outlined in this Privacy Policy. We may retain certain information as required by law or for legitimate business purposes. Users have the choice to opt out of data processing via <Strong>/opt out</Strong> on the Discord bot.</P>

          <Table data={tableData.main} />

          <Note>* Message content is retained for 60 days to allow users to access and export their data. After this period, messages will be deleted.</Note>
          <Note>** User data is retained for up to 3 months to preserve the accuracy and integrity of exported channel snapshots. This ensures that exports reflect the original context of a message, even if the user later deletes their account or changes their profile image. Assets are stored using a least-recently-used (LRU) cache and may be removed sooner if they are not accessed.</Note>

          <P style={{ marginTop: '1.5rem' }}>The following table applies only to server snapshots and has been separated from the above to avoid confusion.</P>

          <Table data={tableData.snapshots} />

          <Note>* Servers are limited to 7 snapshots — the oldest snapshots will be deleted first. Snapshots can be pinned to prevent deletion.</Note>
        </Section>

        <Section number="06" title="Sharing and Disclosure">
          <P>We do <Strong>not</Strong> share or sell your data with any third parties. However, data may be disclosed under these conditions:</P>
          <Ul items={[
            'When required by law (e.g., law enforcement request under U.S. law)',
            'When needed to enforce Discord\'s Terms of Service or protect users',
            'When data is exported by a user, they become responsible for how that data is used',
          ]} />

          <SubHeading>Reporting Illegal Activity</SubHeading>
          <P>While FBI does not monitor content proactively, we reserve the right to report content to appropriate authorities if we become aware of material that violates applicable laws. This includes but is not limited to child sexual abuse material (CSAM), threats of violence, plans of national sabotage, or other criminal content. This includes, but is not limited to, files or avatars stored on our CDN servers, which may be flagged during routine integrity checks. We take these matters very seriously and cooperate with law enforcement where legally required or ethically warranted.</P>
        </Section>

        <Section number="07" title="User Control">
          <P>We value user autonomy and privacy. Users are not required to accept our Privacy Policy explicitly before interacting with the bot. By interacting with the FBI bot, users consent to the collection of public data in accordance with our Privacy Policy. However, users retain the following rights:</P>
          <Ul items={[
            <><Strong>Data Deletion</Strong> — Users can request to have their personal data, including messages and attachments, permanently deleted from our systems. Upon request, any messages, attachments, and identifiable content related to the user will be removed or replaced with the message "Data revoked due to privacy request." Some metadata may be retained for data integrity and security purposes.</>,
            <><Strong>Export Access</Strong> — Server administrators can grant or revoke a user's ability to export channel data. If a user is banned from a server, their export permissions will automatically be revoked until a server admin reverts this.</>,
            <><Strong>Changes to Privacy Preferences</Strong> — Users can request to change their privacy settings or inquire about their data at any time. We will make reasonable efforts to accommodate such requests in accordance with applicable laws and our operational capabilities.</>,
          ]} />
          <P>Please note that while users can control their own data, any pre-existing exports are out of our control and may still contain data before deletion. We recommend that users regularly review their data and request deletion if they no longer wish to have it stored.</P>
        </Section>

        <Section number="08" title="Your Rights">
          <P>As a user of FBI, you have the right to access, correct, and request the deletion of your personal data stored on FBI. These rights apply to all users, regardless of their location.</P>
          <Ul items={[
            <><Strong>Access to Data</Strong> — You have the right to request a copy of your personal data that we store. This includes data like your messages, attachments, and metadata associated with your account. You can request this information at any time by contacting us directly.</>,
            <><Strong>Data Deletion</Strong> — You can request the deletion of your personal data. While some data may be retained for legal and safety reasons, we will remove or anonymize your personal data where possible.</>,
            <><Strong>Rectification of Data</Strong> — If any of your personal data is inaccurate or incomplete, you have the right to request that we correct or update it.</>,
            <><Strong>Data Portability</Strong> — In regions where data portability is required (e.g., under GDPR), you may request that we provide your data in a structured, commonly used, and machine-readable format so that it can be transferred to another service.</>,
            <><Strong>Right to Object</Strong> — You have the right to object to this processing in certain circumstances, such as when you believe your rights override our legitimate interest in retaining or using your data.</>,
          ]} />
          <P>To exercise any of these rights, please contact us through our Discord support server. We will respond to your request within a reasonable timeframe and in accordance with applicable laws.</P>
          <P>If you believe your data rights have been violated, you may contact us or file a complaint with the appropriate data protection authority in your jurisdiction.</P>
        </Section>

        <Section number="09" title="Changes to This Policy">
          <P>We may update this Privacy Policy from time to time. Major changes will be announced in our Discord support server. Continued use of FBI after an update constitutes acceptance of the new terms.</P>
        </Section>

        <Section number="10" title="Contact Us">
          <P>
            If you have any questions about this Policy, please contact us through our Discord support server or by emailing us at{' '}
            <a href="mailto:support@notfbi.dev" style={{ color: 'var(--ember)', textDecoration: 'none', borderBottom: '1px solid #ff480040' }}>
              support@notfbi.dev
            </a>.
          </P>
        </Section>

      </div>
    </main>
  )
}